<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cst</string>
	</array>
	<key>name</key>
	<string>Glaemscribe Charset</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#info-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#changelog-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#char-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#virtual-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#seq-block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>changelog-block</key>
		<dict>
			<key>begin</key>
			<string>(\\beg)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(changelog)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#changelog-entry-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
			</array>
		</dict>
		<key>changelog-entry-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\entry)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\"[^\"]*?\")((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\"[^\"]*?\")((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
		</dict>
		<key>char-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.symbol</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>7</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#symbol</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\char)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\b[a-fA-F0-9]+\b)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(?:(?:(\?)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$))|([^\?]+))</string>
		</dict>
		<key>class-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.symbol</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>7</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[A-Z0-9_]</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\class)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\b[A-Z0-9_]+\b)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(?:(?:(\b[A-Z0-9_]+\b)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$))|(.+))</string>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>\\\*\*</string>
			<key>end</key>
			<string>\*\*\\</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<key>default-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\default)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\b[A-Z0-9_]+\b)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
		</dict>
		<key>info-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\(?:(?!(?:beg|end|entry|char|class|reversed|default)\b)[a-zA-Z_])*)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)([^\s]+|(?:\"[^\"]*?\"))((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
		</dict>
		<key>reversed-statement</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\\reversed)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
		</dict>
		<key>seq-block</key>
		<dict>
			<key>begin</key>
			<string>(\\beg)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(seq)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(\b[A-Z0-9_]+\b)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.symbol</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[A-Z0-9_]</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
		</dict>
		<key>symbol</key>
		<dict>
			<key>match</key>
			<string>[A-Z0-9_]</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<key>virtual-block</key>
		<dict>
			<key>begin</key>
			<string>(\\beg)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(virtual)((?:\s|(?:\\\*\*(?:[^\*\n\r]|(?:\*+[^\*\\\n\r]))*?\*\*+\\))+)(?:(?:(\b[A-Z0-9_]+\b)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$))|(.+))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>7</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#symbol</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>end</key>
			<string>(\\end)((?:\s*?$)|(?:\s*?\\\*\*(?:[^\*]|(?:\*+[^\*\\]))*?\*\*+\\)*?\s*?$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#reversed-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default-statement</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cst</string>
	<key>uuid</key>
	<string>FE33F084-B7B0-11E9-A2A3-2A2AE2DBCCE4</string>
</dict>
</plist>
