<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>glaem</string>
	</array>
	<key>name</key>
	<string>GlaeML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\\\*\*</string>
			<key>end</key>
			<string>\*\*\\</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\\beg|\\end\s*$)\s*(".*?"|[^\s]*)\s*(".*?"|[^\s]*)\s*(".*?"|[^\s]*)\s*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\\[a-zA-Z_]+)\s*(".*"|[^\s]*)\s*(.*)</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.glaem</string>
	<key>uuid</key>
	<string>F261BD11-1AF3-441E-A074-3B0A4C65F61E</string>
</dict>
</plist>
